### ISSUE TITLE
Cannot read property 'writeSync' of undefined

### ISSUE THREAD

**Issue by ghost** [enricocanardi/NodeJS_ST7920#1]
Test nodejs script:

```
var ST7920 = require('st7920');

var lcd = new ST7920({
  sclk: 15, // the controller sclk (clock) pin, "E" on Digole 12864ZW
  sid: 14, // the controller sid (data) pin, "R/W" on Digole 12864ZW
  rst: 18 // the controller reset pin, "RST" on Digole 12864ZW
});

lcd.on('initText',function() {
  lcd.printText(0, 0, "First Row");
  lcd.printText(1, 1, "Second Row");
  lcd.printText(2, 2, "Third Row");
  lcd.printText(3, 3, "Fourth Row");
});
lcd.initText();
```

Platfrom:
```
pi@raspberrypi:~/lcd $ node -v
v6.2.1
pi@raspberrypi:~/lcd $ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Error message:

```
pi@raspberrypi:~/lcd $ node lcd.js
starting LCD
        - Init
        - initText
/home/pi/lcd/node_modules/st7920/ST7920.js:198
        this.sid.writeSync(value);
                ^

TypeError: Cannot read property 'writeSync' of undefined
    at ST7920._sendBit (/home/pi/lcd/node_modules/st7920/ST7920.js:198:10)
    at ST7920._synk (/home/pi/lcd/node_modules/st7920/ST7920.js:206:7)
    at ST7920._sendByte (/home/pi/lcd/node_modules/st7920/ST7920.js:231:7)
    at ST7920.initText (/home/pi/lcd/node_modules/st7920/ST7920.js:84:7)
    at Object.<anonymous> (/home/pi/lcd/lcd.js:15:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

```

**Comment by ghost** [comment]
Nevermind, found your working example in /tests -- That works!
